name: lgf
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - pytorch
  - torchvision
  - ignite==0.2.1
  - imageio
  - pandas
  - matplotlib
  - scikit-learn
  - tensorboardx
  - tqdm
  - pytest
  - pip
  - pip:
    - pyro-ppl
    - torchtestcase
    - pipenv
    - plumbum